W4D4/music/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]

  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, only: [:show, :create, :edit, :update, :destroy] do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:show, :create, :edit, :update, :destroy]

  resources :notes, only: [:create, :destroy]

  root to: "sessions#new"
end

W4D4/music/app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  ord        :integer          not null
#  album_id   :integer          not null
#  lyrics     :string
#  is_bonus   :boolean          default(FALSE), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Track < ApplicationRecord
  validates :title, :ord, :album_id, presence: true
  validates_numericality_of :ord, only_integer: true

  belongs_to :album
  has_many :notes, dependent: :destroy

  has_one :band,
          through: :album,
          source: :band
end

W4D4/music/app/controllers/tracks_controller.rb
class TracksController < AuthenticatedApplicationController
  def show
    @track = Track.find(params[:id])
    render :show
  end

  def new
    @track = Track.new(album_id: params[:album_id])
    @albums = Album.all
    render :new
  end

  def create
    @track = Track.new(track_params)
    if @track.save
      redirect_to track_url(@track)
    else
      flash.now[:errors] = @track.errors.full_messages
      @albums = Album.all
      render :new
    end
  end

  def edit
    @track = Track.find(params[:id])
    @albums = Album.all
    render :edit
  end

  def update
    @track = Track.find(params[:id])
    if @track.update(track_params)
      redirect_to track_url(@track)
    else
      flash.now[:errors] = @track.errors.full_messages
      render :edit
    end
  end

  def destroy
    @track = Track.find(params[:id])
    @album = @track.album
    if @track
      @track.destroy
    else
      flash[:errors] = ["That track does not exist"]
    end
    redirect_to album_url(@album)
  end

  private

  def track_params
    params.require(:track).permit(:title, :ord, :album_id, :lyrics, :is_bonus)
  end
end

W4D4/music/app/views/tracks/_form.html.erb
<% if track.persisted? %>
  <% action_url = track_url(track) %>
  <% submit_string = "Edit Track" %>
<% else %>
  <% action_url = tracks_url %>
  <% submit_string = "Create Track" %>
<% end %>

<form class="" action="<%= action_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <% if track.persisted? %>
    <input type="hidden" name="_method" value="patch">
  <% end %>
  <label>Title
    <input type="text" name="track[title]" value="<%= track.title %>">
  </label>
  <label>Album
    <select name="track[album_id]">
      <% albums.each do |album| %>
        <option value="<%= album.id %>" <%= "selected" if track.album_id == album.id %>><%=album.title%></option>
      <% end %>
    </select>
  </band>
  <label>Ord
    <input type="text" name="track[ord]" value="<%= track.ord %>">
  </label>
  <label>Lyrics
    <textarea name="track[lyrics]"><%= track.lyrics %></textarea>
  </label>
  <label>Bonus Track
    <input type="radio" name="track[is_bonus]" value="true" <%= "checked" if track.is_bonus %>>
  </label>
  <label>Regular Track
    <input type="radio" name="track[is_bonus]" value="false" <%= "checked" unless track.is_bonus %>>
  </label>
  <input type="submit" value="<%= submit_string %>">
</form>

W4D4/music/app/views/tracks/edit.html.erb
<h2>Edit Track</h2>
<%= render "form", track: @track, albums: @albums %>

W4D4/music/app/views/tracks/new.html.erb
<h2>New Track</h2>
<%= render "form", track: @track, albums: @albums %>

W4D4/music/app/views/tracks/show.html.erb
<h2><%= @track.title %></h2>
<p>Ord: <%= @track.ord %></p>
<p>Band: <%= @track.band.name %></p>
<p>Album: <%= @track.album.title %></p>
<p>Type: <%= @track.is_bonus ? "Bonus" : "Regular" %></p>
<%= ugly_lyrics(@track.lyrics) %>
<a href="<%= edit_track_url %>">Edit Track</a>
<form action="<% track_url(@track) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="delete">
  <button>Delete Track</button>
</form>
<a href="<%= album_url(@track.album) %>">View Album</a>
<a href="<%= band_url(@track.band) %>">View Band</a>

<h3>Add a note:</h3>
<%= render "notes/form", track_id: @track.id %>

<h3>Notes</h3>
<% @track.notes.includes(:user).sort_by(&:created_at).reverse!.each_with_index do |note, idx| %>
  <%= render "notes/note", note: note, idx: idx %>
<% end %>