W4D4/music/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]

  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, only: [:show, :create, :edit, :update, :destroy] do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:show, :create, :edit, :update, :destroy]

  resources :notes, only: [:create, :destroy]

  root to: "sessions#new"
end

W4D4/music/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Music</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <header>
      <h1>Music App</h1>
      <% if logged_in? %>
        <p>Hello <%= current_user.email %></p>
        <form action="<%= session_url %>" method="post">
          <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
          <input type="hidden" name="_method" value="delete">
          <button>Log Out</button>
        </form>
      <% else %>
        <a href="<%= new_session_url %>">Log In</a>
        <a href="<%= new_user_url %>">Sign Up</a>
      <% end %>
    </header>
    <% if flash.key?(:errors) %>
      <% flash[:errors].each do |error| %>
        <div class="error"><%= error %></div>
      <% end %>
    <% end %>
    <%= yield %>
  </body>
</html>