W4D4/music/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]

  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, only: [:show, :create, :edit, :update, :destroy] do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:show, :create, :edit, :update, :destroy]

  resources :notes, only: [:create, :destroy]

  root to: "sessions#new"
end

W4D4/music/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :email, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  before_validation :generate_session_token
  attr_reader :password

  has_many :notes

  def self.find_by_credentials(email, password)
    user = self.find_by_email(email)
    if user && user.is_password?(password)
      user
    end
  end

  def generate_session_token
    self.session_token ||= SecureRandom::base64(16)
  end

  def reset_session_token!
    self.session_token = SecureRandom::base64(16)
    self.save!
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end
end

W4D4/music/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    render :show
  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      mail = UserMailer.welcome_emaill(@user)
      mail.deliver_now
      log_in!(@user)
      redirect_to bands_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

W4D4/music/app/views/users/index.html.erb
<% @users.each do |user| %>
  <ul>
    <li><%= user.email %></li>
  </ul>
<% end %>

W4D4/music/app/views/users/new.html.erb
<h2>Sign Up</h2>
<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>Email
    <input type="text" name="user[email]">
  </label>
  <label>Password
    <input type="password" name="user[password]">
  </label>
  <input type="submit" value="Sign Up">
</form>

W4D4/music/app/views/users/show.html.erb
<h2>Profile</h2>
<ul>
  <li><%= @user.email %></li>
</ul>